### PR TITLE
Add Slimeda function specification

### PR DESCRIPTION
**Pull request by thayeylolu**
I listed the functions specifications for slimeda in the README.md

### CODE REVIEW

**Comment by khalidcawl** [comment]
Hi Taiwo. Thank you for writing up the specifications. It looks good, but for the first two functions, I think we're returning chart objects and not images. I am not 100% sure about this either, but we can discuss it during our meeting.

**Comment by khalidcawl** [comment]
This PR has conflicts. Can you please pull the main, fix conflicts local, and then update the PR? Thanks. @thayeylolu

**Comment by thayeylolu** [comment]
Thanks Khalid. Will do that!

**Comment by khalidcawl** [comment]
Hi @thayeylolu , sorry to keep this pull request dragging. But your changes seem to overwrite Anthea's. Please make sure both changes are there. In the future when merging conflicts, choose "keep both" when both your change and the other author's change should be included.

**Review by Anthea98 — APPROVED** [review]

**Pull request merged**
